title: Mei Irawati # your name (or website title) here
logo: "/images/fotoku.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Data Analyst</b> 
  <br></br>
  <b>I am an undergraduate student of the Faculty of Information Technology Study Program 
  Informatics Engineering Satya Wacana Christian University</b>
  <br></br>
  <a href="https://www.linkedin.com/in/mei-irawati-b50019222/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
